name: network_info
description: A standalone Flutter package for retrieving network information (public and local IP addresses)
version: 1.0.2
homepage: https://github.com/sepehrTabeian/network_info
repository: https://github.com/sepehrTabeian/network_info
issue_tracker: https://github.com/sepehrTabeian/network_info/issues

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.2
  get_it: ^8.2.0
  http: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.25.8
  test_core: ^0.6.11
  mocktail: ^1.0.4
